-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:7f829da68e62dcefd9f7e78a8f81afdb$
-- 

return {
	texture = 'objects_sheet_1.png',
	frames = {
			{
				name = "box1",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.716797, v0 = 0.126953, u1 = 0.966797, v1 = 0.251953 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick1",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.382812, v0 = 0.50293, u1 = 0.507812, v1 = 0.56543 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick1_cracked_1",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.507812, v0 = 0.482422, u1 = 0.632812, v1 = 0.544922 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick1_cracked_2",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.671875, v0 = 0.439453, u1 = 0.796875, v1 = 0.501953 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick2",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.800781, v0 = 0.376953, u1 = 0.925781, v1 = 0.439453 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick3",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.382812, v0 = 0.44043, u1 = 0.507812, v1 = 0.50293 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick3_cracked_1",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.546875, v0 = 0.419922, u1 = 0.671875, v1 = 0.482422 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick3_cracked_2",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.675781, v0 = 0.376953, u1 = 0.800781, v1 = 0.439453 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "circle_bad",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 55 },
				uvRect = { u0 = 0.796875, v0 = 0.494141, u1 = 0.904297, v1 = 0.547852 },
				spriteSourceSize = { width = 55, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "circle_bad_eye",
				spriteColorRect = { x = 0, y = 0, width = 6, height = 5 },
				uvRect = { u0 = 0.970703, v0 = 0, u1 = 0.982422, v1 = 0.00488281 },
				spriteSourceSize = { width = 6, height = 5 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "circle_bad_saw",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 84 },
				uvRect = { u0 = 0.382812, v0 = 0.358398, u1 = 0.546875, v1 = 0.44043 },
				spriteSourceSize = { width = 84, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "diamond",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 63 },
				uvRect = { u0 = 0.546875, v0 = 0.358398, u1 = 0.675781, v1 = 0.419922 },
				spriteSourceSize = { width = 66, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lamp_1",
				spriteColorRect = { x = 0, y = 0, width = 105, height = 128 },
				uvRect = { u0 = 0.716797, v0 = 0.251953, u1 = 0.921875, v1 = 0.376953 },
				spriteSourceSize = { width = 105, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "moon",
				spriteColorRect = { x = 8, y = 8, width = 367, height = 367 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.716797, v1 = 0.358398 },
				spriteSourceSize = { width = 383, height = 383 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "rock",
				spriteColorRect = { x = 0, y = 0, width = 196, height = 170 },
				uvRect = { u0 = 0, v0 = 0.358398, u1 = 0.382812, v1 = 0.524414 },
				spriteSourceSize = { width = 196, height = 170 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "scissors_01_bottom",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 61 },
				uvRect = { u0 = 0.632812, v0 = 0.501953, u1 = 0.732422, v1 = 0.561523 },
				spriteSourceSize = { width = 51, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "scissors_01_top",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 78 },
				uvRect = { u0 = 0.921875, v0 = 0.251953, u1 = 0.970703, v1 = 0.328125 },
				spriteSourceSize = { width = 25, height = 78 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "spiral",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 56 },
				uvRect = { u0 = 0.796875, v0 = 0.439453, u1 = 0.910156, v1 = 0.494141 },
				spriteSourceSize = { width = 58, height = 56 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "star",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 130 },
				uvRect = { u0 = 0.716797, v0 = 0, u1 = 0.970703, v1 = 0.126953 },
				spriteSourceSize = { width = 130, height = 130 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

