-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
<<<<<<< Updated upstream
-- $TexturePacker:SmartUpdate:61c7cecfb962b20388d6cd7272c5f135$
=======
-- $TexturePacker:SmartUpdate:9b682e8c1f80a76f4621e1a8e29cf216$
>>>>>>> Stashed changes
-- 

return {
	texture = 'objects_sheet_1.png',
	frames = {
			{
				name = "box1",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0, v0 = 0.462891, u1 = 0.25, v1 = 0.587891 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick1",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.472656, v0 = 0.485352, u1 = 0.597656, v1 = 0.547852 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick1_cracked_1",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.490234, v0 = 0.422852, u1 = 0.615234, v1 = 0.485352 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick1_cracked_2",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.490234, v0 = 0.360352, u1 = 0.615234, v1 = 0.422852 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_1",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 128 },
				uvRect = { u0 = 0, v0 = 0.125, u1 = 0.625, v1 = 0.25 },
				spriteSourceSize = { width = 320, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_2",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 128 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.625, v1 = 0.125 },
				spriteSourceSize = { width = 320, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_3",
				spriteColorRect = { x = 0, y = 0, width = 294, height = 113 },
				uvRect = { u0 = 0, v0 = 0.25, u1 = 0.574219, v1 = 0.360352 },
				spriteSourceSize = { width = 294, height = 113 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_4",
				spriteColorRect = { x = 0, y = 0, width = 151, height = 80 },
				uvRect = { u0 = 0.625, v0 = 0.168945, u1 = 0.919922, v1 = 0.24707 },
				spriteSourceSize = { width = 151, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_5",
				spriteColorRect = { x = 0, y = 0, width = 251, height = 105 },
				uvRect = { u0 = 0, v0 = 0.360352, u1 = 0.490234, v1 = 0.462891 },
				spriteSourceSize = { width = 251, height = 105 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lamp_1",
				spriteColorRect = { x = 0, y = 0, width = 105, height = 128 },
<<<<<<< Updated upstream
				uvRect = { u0 = 0.654297, v0 = 0.499023, u1 = 0.859375, v1 = 0.624023 },
=======
				uvRect = { u0 = 0.597656, v0 = 0.540039, u1 = 0.802734, v1 = 0.665039 },
>>>>>>> Stashed changes
				spriteSourceSize = { width = 105, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "player",
<<<<<<< Updated upstream
				spriteColorRect = { x = 0, y = 0, width = 110, height = 99 },
				uvRect = { u0 = 0.439453, v0 = 0.499023, u1 = 0.654297, v1 = 0.595703 },
				spriteSourceSize = { width = 110, height = 99 },
=======
				spriteColorRect = { x = 0, y = 0, width = 114, height = 99 },
				uvRect = { u0 = 0.25, v0 = 0.462891, u1 = 0.472656, v1 = 0.55957 },
				spriteSourceSize = { width = 114, height = 99 },
>>>>>>> Stashed changes
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "player_aim",
				spriteColorRect = { x = 1, y = 1, width = 173, height = 173 },
				uvRect = { u0 = 0.625, v0 = 0, u1 = 0.962891, v1 = 0.168945 },
				spriteSourceSize = { width = 175, height = 175 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
<<<<<<< Updated upstream
				name = "player_focused",
				spriteColorRect = { x = 0, y = 0, width = 114, height = 99 },
				uvRect = { u0 = 0, v0 = 0.462891, u1 = 0.222656, v1 = 0.55957 },
				spriteSourceSize = { width = 114, height = 99 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "player_sad",
				spriteColorRect = { x = 0, y = 0, width = 111, height = 99 },
				uvRect = { u0 = 0.222656, v0 = 0.462891, u1 = 0.439453, v1 = 0.55957 },
				spriteSourceSize = { width = 111, height = 99 },
=======
				name = "rock",
				spriteColorRect = { x = 0, y = 0, width = 196, height = 170 },
				uvRect = { u0 = 0.615234, v0 = 0.374023, u1 = 0.998047, v1 = 0.540039 },
				spriteSourceSize = { width = 196, height = 170 },
>>>>>>> Stashed changes
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "scissors_01_bottom",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 61 },
				uvRect = { u0 = 0.878906, v0 = 0.24707, u1 = 0.978516, v1 = 0.306641 },
				spriteSourceSize = { width = 51, height = 61 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "scissors_01_top",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 78 },
				uvRect = { u0 = 0.919922, v0 = 0.168945, u1 = 0.96875, v1 = 0.245117 },
				spriteSourceSize = { width = 25, height = 78 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "star",
				spriteColorRect = { x = 0, y = 0, width = 130, height = 130 },
				uvRect = { u0 = 0.625, v0 = 0.24707, u1 = 0.878906, v1 = 0.374023 },
				spriteSourceSize = { width = 130, height = 130 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

