-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:24e60d9997378ddff1e2afeb08e5bd1b$
-- 

return {
	texture = 'patterns_sheet_1.png',
	frames = {
			{
				name = "p1",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 50 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.78125, v1 = 0.78125 },
				spriteSourceSize = { width = 50, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

