-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:bdb662ce2baca06fd4b56f451ec6eaad$
-- 

return {
	texture = 'perm_sheet_1.png',
	frames = {
			{
				name = "cloud_1",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 128 },
				uvRect = { u0 = 0, v0 = 0.125, u1 = 0.625, v1 = 0.25 },
				spriteSourceSize = { width = 320, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_2",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 128 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.625, v1 = 0.125 },
				spriteSourceSize = { width = 320, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_3",
				spriteColorRect = { x = 0, y = 0, width = 294, height = 113 },
				uvRect = { u0 = 0, v0 = 0.25, u1 = 0.574219, v1 = 0.360352 },
				spriteSourceSize = { width = 294, height = 113 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_4",
				spriteColorRect = { x = 0, y = 0, width = 151, height = 80 },
				uvRect = { u0 = 0.625, v0 = 0.168945, u1 = 0.919922, v1 = 0.24707 },
				spriteSourceSize = { width = 151, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_5",
				spriteColorRect = { x = 0, y = 0, width = 251, height = 105 },
				uvRect = { u0 = 0, v0 = 0.420898, u1 = 0.490234, v1 = 0.523438 },
				spriteSourceSize = { width = 251, height = 105 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "heart",
				spriteColorRect = { x = 0, y = 0, width = 83, height = 83 },
				uvRect = { u0 = 0, v0 = 0.523438, u1 = 0.162109, v1 = 0.604492 },
				spriteSourceSize = { width = 83, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "heart_bk",
				spriteColorRect = { x = 0, y = 0, width = 93, height = 94 },
				uvRect = { u0 = 0.791016, v0 = 0.40332, u1 = 0.972656, v1 = 0.495117 },
				spriteSourceSize = { width = 93, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pause_button",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 84 },
				uvRect = { u0 = 0.705078, v0 = 0.495117, u1 = 0.869141, v1 = 0.577148 },
				spriteSourceSize = { width = 84, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "player",
				spriteColorRect = { x = 0, y = 0, width = 110, height = 99 },
				uvRect = { u0 = 0.490234, v0 = 0.44043, u1 = 0.705078, v1 = 0.537109 },
				spriteSourceSize = { width = 110, height = 99 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "player_aim",
				spriteColorRect = { x = 1, y = 1, width = 173, height = 173 },
				uvRect = { u0 = 0.625, v0 = 0, u1 = 0.962891, v1 = 0.168945 },
				spriteSourceSize = { width = 175, height = 175 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player_focused",
				spriteColorRect = { x = 0, y = 0, width = 114, height = 99 },
				uvRect = { u0 = 0.625, v0 = 0.24707, u1 = 0.847656, v1 = 0.34375 },
				spriteSourceSize = { width = 114, height = 99 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "player_sad",
				spriteColorRect = { x = 0, y = 0, width = 111, height = 99 },
				uvRect = { u0 = 0.574219, v0 = 0.34375, u1 = 0.791016, v1 = 0.44043 },
				spriteSourceSize = { width = 111, height = 99 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "progress_bar",
				spriteColorRect = { x = 0, y = 0, width = 269, height = 26 },
				uvRect = { u0 = 0, v0 = 0.395508, u1 = 0.525391, v1 = 0.420898 },
				spriteSourceSize = { width = 269, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "progress_bar_bk",
				spriteColorRect = { x = 0, y = 0, width = 286, height = 36 },
				uvRect = { u0 = 0, v0 = 0.360352, u1 = 0.558594, v1 = 0.395508 },
				spriteSourceSize = { width = 286, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "trophy",
				spriteColorRect = { x = 0, y = 0, width = 66, height = 87 },
				uvRect = { u0 = 0.847656, v0 = 0.318359, u1 = 0.976562, v1 = 0.40332 },
				spriteSourceSize = { width = 66, height = 87 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "x",
				spriteColorRect = { x = 16, y = 16, width = 73, height = 73 },
				uvRect = { u0 = 0.847656, v0 = 0.24707, u1 = 0.990234, v1 = 0.318359 },
				spriteSourceSize = { width = 105, height = 105 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

