-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:68867ede10b642d8588c6d9808a9a9dc$
-- 

return {
	texture = 'objects_sheet_1.png',
	frames = {
			{
				name = "box1",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.25, v0 = 0.462891, u1 = 0.5, v1 = 0.587891 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick1",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.490234, v0 = 0.360352, u1 = 0.615234, v1 = 0.422852 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick1_cracked_1",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.875, v0 = 0.30957, u1 = 1, v1 = 0.37207 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "brick1_cracked_2",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.875, v0 = 0.24707, u1 = 1, v1 = 0.30957 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_1",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 128 },
				uvRect = { u0 = 0, v0 = 0.125, u1 = 0.625, v1 = 0.25 },
				spriteSourceSize = { width = 320, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_2",
				spriteColorRect = { x = 0, y = 0, width = 320, height = 128 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.625, v1 = 0.125 },
				spriteSourceSize = { width = 320, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_3",
				spriteColorRect = { x = 0, y = 0, width = 294, height = 113 },
				uvRect = { u0 = 0, v0 = 0.25, u1 = 0.574219, v1 = 0.360352 },
				spriteSourceSize = { width = 294, height = 113 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_4",
				spriteColorRect = { x = 0, y = 0, width = 151, height = 80 },
				uvRect = { u0 = 0.625, v0 = 0.168945, u1 = 0.919922, v1 = 0.24707 },
				spriteSourceSize = { width = 151, height = 80 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cloud_5",
				spriteColorRect = { x = 0, y = 0, width = 251, height = 105 },
				uvRect = { u0 = 0, v0 = 0.360352, u1 = 0.490234, v1 = 0.462891 },
				spriteSourceSize = { width = 251, height = 105 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "player",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0, v0 = 0.462891, u1 = 0.25, v1 = 0.587891 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "player_aim",
				spriteColorRect = { x = 1, y = 1, width = 173, height = 173 },
				uvRect = { u0 = 0.625, v0 = 0, u1 = 0.962891, v1 = 0.168945 },
				spriteSourceSize = { width = 175, height = 175 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "player_lit",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.615234, v0 = 0.37207, u1 = 0.865234, v1 = 0.49707 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "star",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 128 },
				uvRect = { u0 = 0.625, v0 = 0.24707, u1 = 0.875, v1 = 0.37207 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

