-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:0167e6b1f46656126c209edf8b454e6e$
-- 

return {
	texture = 'tiles_background.png',
	frames = {
			{
				name = "noise_1",
				spriteColorRect = { x = 0, y = 0, width = 512, height = 512 },
				uvRect = { u0 = 0.5, v0 = 0, u1 = 1, v1 = 0.5 },
				spriteSourceSize = { width = 512, height = 512 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "noise_2",
				spriteColorRect = { x = 0, y = 0, width = 512, height = 512 },
				uvRect = { u0 = 0, v0 = 0.5, u1 = 0.5, v1 = 1 },
				spriteSourceSize = { width = 512, height = 512 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "noise_3",
				spriteColorRect = { x = 0, y = 0, width = 512, height = 512 },
				uvRect = { u0 = 0, v0 = 0.5, u1 = 0.5, v1 = 1 },
				spriteSourceSize = { width = 512, height = 512 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "white",
				spriteColorRect = { x = 0, y = 0, width = 512, height = 512 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.5, v1 = 0.5 },
				spriteSourceSize = { width = 512, height = 512 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

