-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:9e33d5cded8f7b47b74c62c52a4b3fd1$
-- 

return {
	texture = 'tiles_sheet_1.png',
	frames = {
			{
				name = "edge_bottom",
				spriteColorRect = { x = 0, y = 0, width = 192, height = 64 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.75, v1 = 1 },
				spriteSourceSize = { width = 192, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "sq_black_64x64",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.75, v0 = 0, u1 = 1, v1 = 1 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

